# Generated by Django 4.1.5 on 2023-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(default='hi'),
        ),
    ]
