# Generated by Django 4.1.5 on 2023-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_meeting_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(),
        ),
    ]
