# Generated by Django 4.1.5 on 2023-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_meeting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='qr_image',
            field=models.ImageField(default='a.png', upload_to=''),
        ),
    ]
