# Generated by Django 4.1.5 on 2023-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_meeting_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='qr_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
