# Generated by Django 4.1.3 on 2023-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_meeting_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='sdssd', max_length=255),
        ),
    ]
